version: 2
jobs:
  working_directory: ~/open-wc-starter-app
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:8
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: init
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test